### ISSUE TITLE
responding to all devices

### ISSUE THREAD

**Issue by odelay** [gerritjandebruin/ha-rtl#2]
Hi,

I try to configure the same doorbell with the same rlt receiver. It is working fine but it picks up other devices as well including a notification. Could you tell me if I have configured something wrong?
my configuration looks as follow:

```
frequencies:
  - 433920000
hop_interval: 10
devices:
  - protocol: 51
    automation_type: device_automation
    trigger_type: action
    trigger_subtype: button_1
    manufacturer: Klik
    name: doorbell
    id: '38298462'
    model: Proove-Security
discovery_prefix_mqtt: homeassistant

- id: '1642847457529'
  alias: Deurbel Notificatie
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b4eea38e54d986592d9d8b70bb089e03
    type: action
    subtype: button_1
    discovery_id: rtl433
  condition: []
  action:
  - service: notify.mobile_app_oneplus_6
    data:
      message: Deurbel!!
  mode: single
```
appreciate your work! 
kind regards,
Peter

**Comment by gerritjandebruin** [comment]
Hi Peter,

Can you try replacing `id` for `house_code`? Like so:
```
frequencies:
  - 433920000
hop_interval: 10
devices:
  - protocol: 51
    automation_type: device_automation
    trigger_type: action
    trigger_subtype: button_1
    manufacturer: Klik
    name: doorbell
    house_code: '38298462'
    model: Proove-Security
discovery_prefix_mqtt: homeassistant

- id: '1642847457529'
  alias: Deurbel Notificatie
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b4eea38e54d986592d9d8b70bb089e03
    type: action
    subtype: button_1
    discovery_id: rtl433
  condition: []
  action:
  - service: notify.mobile_app_oneplus_6
    data:
      message: Deurbel!!
  mode: single 
```

Thanks!

Gerrit Jan

**Comment by odelay** [comment]
That helps, although you still needs an id, it looks like this now:

```
frequencies:
  - 433920000
hop_interval: 10
devices:
  - protocol: 51
    automation_type: device_automation
    trigger_type: button_short_press
    trigger_subtype: button
    manufacturer: Kaku
    name: doorbell
    id: '38298462'
    house_code: '38298462'
    model: Proove-Security
discovery_prefix_mqtt: homeassistant
```
And the automation:

```
- id: '1643900795255'
  alias: Deurbel Notificatie
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: b4eea38e54d986592d9d8b70bb089e03
    type: button_short_press
    subtype: button
    discovery_id: rtl433
  condition: []
  action:
  - service: notify.mobile_app_oneplus_6
    data:
      message: Deurbel!
  mode: single
```
I still have 2 small issues:
- a single doorbell press gives multiple notification on my mobile
- After a reboot of HA it is not working anymore, when you look in the UI automation it shows an Unknown trigger.
  When I restart your Add-on it is solved.

Any idea what can cause this?

thanks again!
Peter

**Comment by gerritjandebruin** [comment]
Hi Peter,

I made some changes to the addon, which are now in v3.0.0.
Note that there is a breaking change, the entry `house_code` should not be provided anymore.
I updated the documentation as well.
It hopefully solves the problem you experienced at rebooting.
If not, can you please send the add-on logs you see directly after starting HA?

Regarding your second problem, this actually has to do with your doorbell.
It send some regular patterns in the ether, which are all separately detected by RTL_433.
The solution is rather easy though, just make your automation somewhat smarter.
You can add a delay at the end of all the actions.
Since you are already using mode `single', this should be sufficient to only perform the automation once.

Best,

Gerrit-Jan

**Comment by odelay** [comment]
Thanks for the delay tip that works fine, still have the problem after a reboot, the log doesn't tell anything. Probably something to do with my HA setup, as it runs on Proxmox and hardware is passthrough to the VM. But I fixed it with an automation to restart it after a reboot: 

```
  alias: HA-RTL Restart
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: 28809773_ha-rtl
  mode: single
```

regards,
Peter
